### ISSUE TITLE
Add unit tests for markdown extensions

### ISSUE THREAD

**Issue by mrdrogdrog** [hedgedoc/react-client#1785] opened 2022-01-16 20:51 UTC
**Is your feature request related to a problem? Please describe.**
Most of our markdown extensions aren't tested. Some of them are covered with e2e test suites.

**Describe the solution you'd like**
Unit test the markdown extensions.

**Describe alternatives you've considered**
Use e2e tests for the extensions. The downsides are that e2e tests take way to long for all the possibilities. They should only be used to test a combination of the features.

**Comment by DerMolly** [comment] 2022-11-22 22:51
duplicate of https://github.com/hedgedoc/hedgedoc/issues/2909

**Closed by DerMolly** 2022-11-22 22:51 UTC
Labels: type: code quality enhancement
