### ISSUE TITLE
Clickable links in editor

### ISSUE THREAD

**Issue by heinrichreimer** [hedgedoc/react-client#1607] opened 2021-10-30 18:59 UTC
**Is your feature request related to a problem? Please describe.**
I can't click links in the Markdown editor.

**Describe the solution you'd like**
Many editors offer opening a link (web or email) by clicking on it in the editor while holding `Cmd` or so.

**Describe alternatives you've considered**
Alternatively one can simply open the document preview

**Additional context**

**Comment by mrdrogdrog** [comment] 2021-10-30 22:25
Duplicate of #951

**Closed** 2021-10-30 22:25 UTC

**Comment by heinrichreimer** [comment] 2021-10-31 08:42
Sorry for the duplicate :see_no_evil:
