### ISSUE TITLE
UI Test loads with no view mode in Chrome

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/react-client#1113] opened 2021-03-16 21:42 UTC
**Description**
After pasting `https://ui-test.hedgedoc.org/n/features` into the Chrome Omnibox, the frontend only shows a big black box:
![grafik](https://user-images.githubusercontent.com/5023650/111382216-fcdd8080-86a6-11eb-8be1-5a299efe4a08.png)
The dev tools show a variety of messages:
![grafik](https://user-images.githubusercontent.com/5023650/111382252-0b2b9c80-86a7-11eb-9d48-c396b05bea88.png)
This behavior persisted over multiple reloads with cache disabled.

Manually selecting the "both" view mode switched to the correct mode after a short delay and caused two more warnings:
![grafik](https://user-images.githubusercontent.com/5023650/111382358-2bf3f200-86a7-11eb-9288-610b18434988.png)

After that the issue was not reproducible anymore.

**To Reproduce**
1. Open the UI test in Chrome
2. ...be lucky?

**Expected behavior**
The frontend shows one of the three view modes without the user having to manually select one.

**Your Setup:**
 - OS: Arch
 - Browser with version
   - Chrome 89.0.4389.90
 - HedgeDoc version 
     - dev-35b548d

**Comment by mrdrogdrog** [comment] 2021-03-16 21:48
I tested it with exact this browser version aaaand.. can't reproduce. Something must be wrong with your setup.

**Comment by mrdrogdrog** [comment] 2021-03-16 21:51
For a short time we had a broken service worker. Check if it is still registered in your browser (dev tools > Applications > Service Workers > unregister every service worker there)

**Comment by ErikMichelson** [comment] 2021-03-17 11:02
This likely happens because we changed `editorConfig` local-storage syntax from `editorMode: 1, 2, 3` to `editorMode: view, both, edit`. Clear your local-storage and try it again.

**Comment by mrdrogdrog** [comment] 2021-03-17 11:04
@ErikMichelson maybe we should change the fallback. And write it back if we use it.

**Comment by ErikMichelson** [comment] 2021-03-17 21:16
Well we currently do not verify the data at all (`return JSON.parse(stored) as EditorConfig`). I doubt that we really need to test each property - especially as this problem only appears for regular ui-test users.
Also note that once you select one of the editor modes, the locally stored config will be corrected.

**Comment by mrdrogdrog** [comment] 2021-03-18 20:24
Yes, but a type cast doesn't verify the data we read. I think it would be better to check the data for plausability.

**Comment by ErikMichelson** [comment] 2021-06-21 09:39
For API response data validation we're tracking the progress in #1219.
As this seems to be solved, I'm going to close this now.

**Closed by ErikMichelson** 2021-06-21 09:39 UTC
Labels: status: can't reproduce, type: bug
