### ISSUE TITLE
Unwanted mermaid titles

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/react-client#1815] opened 2022-01-29 18:24 UTC
**Description**
Mermaid diagrams get titles despite not being configured to have one.

**To Reproduce**
1. Go to [https://hedgedoc.dev/n/features](https://hedgedoc.dev/n/features)
2. Paste this [markdown](https://pastebin.com/MvAAGbeJ)

**Expected behavior**
The 2nd diagram not getting a title.

**Screenshots**

![Bildschirmfoto 2022-01-29 um 19 12 39](https://user-images.githubusercontent.com/3978662/151672477-d9f46774-45ef-4591-9ef7-b16584afd8fd.png)

**Comment by DerMolly** [comment] 2022-01-29 18:42
I suspect the problem lies with a non-proper reinitialization of meramid between the renders…
Cursiously HedgeDoc seems to do this right as can be seen [here](https://demo.hedgedoc.org/nTG5aw_0Q5W4Eb-okDpdMQ#).

**Comment by ErikMichelson** [comment] 2022-07-09 10:07
This seems to have been resolved in the meantime as I cannot reproduce it with the supplied markdown example.

**Closed by ErikMichelson** 2022-07-09 10:07 UTC
Labels: type: bug, scope: renderer

**Comment by mrdrogdrog** [comment] 2022-07-09 10:52
Confirmed
